version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: it_jamaate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./media:/app/media
      - .env:/app/.env

volumes:
  postgres_data: